package com.bumbumapps.stylishtext.activities;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.view.View;

import com.bumbumapps.stylishtext.adapters.EmoticonsAdapter;
import com.bumbumapps.stylishtext.R;
import com.bumbumapps.stylishtext.model.EmotiModel;
import com.google.android.material.appbar.MaterialToolbar;

import java.util.ArrayList;
import java.util.List;

public class EmoticonsActivity extends AppCompatActivity {
    List<EmotiModel> emotiModels = new ArrayList<>();
    RecyclerView recyclerView;
    String name;
    int position;
    MaterialToolbar materialToolbar;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_emoticons);
        materialToolbar = findViewById(R.id.toolbar);
        materialToolbar.setVisibility(View.VISIBLE);
        setSupportActionBar(materialToolbar);
        if (getSupportActionBar() != null){
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        }
        //Firebase Analytics
//        mFirebaseAnalytics = FirebaseAnalytics.getInstance(this);
//        Bundle bundle = new Bundle();
//        bundle.putString(FirebaseAnalytics.Param.ITEM_ID, "id");
//        bundle.putString(FirebaseAnalytics.Param.ITEM_NAME, "emoticons_activity");
//        bundle.putString(FirebaseAnalytics.Param.CONTENT_TYPE, "activity");
//        mFirebaseAnalytics.logEvent(FirebaseAnalytics.Event.SELECT_CONTENT, bundle);
        this.name = getIntent().getStringExtra("image");
        this.position = getIntent().getIntExtra("P", 0);
        int i = this.position;
        if (i == 0) {
            getSupportActionBar().setTitle("Love");
            emotiModels.add(new EmotiModel(1  , "♥‿♥"));
            emotiModels.add(new EmotiModel(2  , "★~(◡‿◡✿)"));
            emotiModels.add(new EmotiModel(3  , "(ノ・ω・)ノ"));
            emotiModels.add(new EmotiModel(4  , "★~(◡︿◕✿)"));
            emotiModels.add(new EmotiModel(5  , "♥╣[-_-]╠♥"));
            emotiModels.add(new EmotiModel(6  , "（⌒_⌒）"));
            emotiModels.add(new EmotiModel(7  , ">‿‿◕"));
            emotiModels.add(new EmotiModel(8  , "★~(◡△◕✿)"));
            emotiModels.add(new EmotiModel(9  , "⎝ᄽ⏝⏠⎠"));
            emotiModels.add(new EmotiModel(10 , "(~￣▽￣)~"));
            emotiModels.add(new EmotiModel(11 , "★~(◡﹏⊙✿)"));
            emotiModels.add(new EmotiModel(12 , "★~(◠﹏◕✿)"));
            emotiModels.add(new EmotiModel(13 , "(◕‿-)"));
            emotiModels.add(new EmotiModel(14 , "★~(◡﹏◕✿)"));
            emotiModels.add(new EmotiModel(15 , "★~(◠﹏⊙✿)"));
            emotiModels.add(new EmotiModel(16 , "★~(◠ω◕✿)"));
            emotiModels.add(new EmotiModel(17 , "♥╭╮♥"));
            emotiModels.add(new EmotiModel(18 , "★~(◡‿⊙✿)"));
            emotiModels.add(new EmotiModel(19 , "(｡♥‿♥｡)"));
            emotiModels.add(new EmotiModel(20 , "★~(◡△⊙✿)"));
            emotiModels.add(new EmotiModel(21 , "★~(◠‿◕✿)"));
            emotiModels.add(new EmotiModel(22 , "v(=∩_∩=)ﾌ"));
            emotiModels.add(new EmotiModel(23 , "♥╭╮♥"));
            emotiModels.add(new EmotiModel(24 , "(ΘεΘ"));
            emotiModels.add(new EmotiModel(25 , "★~(◡‿◕✿)"));
            emotiModels.add(new EmotiModel(26 , "★~(◡ω◕✿)"));
            emotiModels.add(new EmotiModel(27 , "( ^▽^)σ)~O~)"));
            emotiModels.add(new EmotiModel(28 , "★~(◠△◕✿)"));
            emotiModels.add(new EmotiModel(29 , "(✿ ♥‿♥)"));
            emotiModels.add(new EmotiModel(30 , "★~(◠△⊙✿)"));
            emotiModels.add(new EmotiModel(31 , "(╯3╰)"));
            emotiModels.add(new EmotiModel(32 , "★~(◠ω⊙✿)"));
            emotiModels.add(new EmotiModel(33 , "★~(◡△◡✿)"));
            emotiModels.add(new EmotiModel(34 , "★~(◡﹏◡✿)"));
            emotiModels.add(new EmotiModel(35 , "(●´ω｀●)"));
            emotiModels.add(new EmotiModel(36 , "★~(◡︿⊙✿)"));
            emotiModels.add(new EmotiModel(37 , "☼.☼"));
            emotiModels.add(new EmotiModel(38 , "★~(◠︿⊙✿)"));
            emotiModels.add(new EmotiModel(39 , "★~(◡ω◡✿)"));
            emotiModels.add(new EmotiModel(40 , "ヘ(^_^ヘ)"));
            emotiModels.add(new EmotiModel(41 , "(n˘v˘•)¬"));
            emotiModels.add(new EmotiModel(42 , "( ･_･)♡"));
            emotiModels.add(new EmotiModel(43 , "★~(◡ω⊙✿)"));
            emotiModels.add(new EmotiModel(44 , "(●♡∀♡)"));
            emotiModels.add(new EmotiModel(45 , "(｡♥‿♥｡)"));
            emotiModels.add(new EmotiModel(46 , "(♥ω♥ ) ~♪"));
            emotiModels.add(new EmotiModel(47 , "(♥ω♥*)"));
            emotiModels.add(new EmotiModel(48 , "(✿ ♥‿♥)"));
            emotiModels.add(new EmotiModel(49 , "✿♥‿♥✿"));
            emotiModels.add(new EmotiModel(50 , "乂❤‿❤乂"));
            emotiModels.add(new EmotiModel(51 , "٩(♡ε♡ )۶"));
            emotiModels.add(new EmotiModel(52 , "ლζ*♡ε♡*ζლ"));
            emotiModels.add(new EmotiModel(53 , "⊂（♡⌂♡）⊃"));
            emotiModels.add(new EmotiModel(54 , "(๑♡3♡๑)"));
            emotiModels.add(new EmotiModel(55 , "(๑♡⌓♡๑)"));
            emotiModels.add(new EmotiModel(56 , "♱♡‿♡♰"));
            emotiModels.add(new EmotiModel(57 , "⊆♥_㇁♥⊇"));
            emotiModels.add(new EmotiModel(58 , "(●♡∀♡))ヾ☆*。"));
            emotiModels.add(new EmotiModel(59 , "໒( ♥ ◡ ♥ )७"));
            emotiModels.add(new EmotiModel(60 , "༼♥ل͜♥༽"));
            emotiModels.add(new EmotiModel(61 , "(灬♥ω♥灬)"));
            emotiModels.add(new EmotiModel(62 , "(‘∀’●)♡"));
            emotiModels.add(new EmotiModel(63 , "(´∀｀)♡"));
            emotiModels.add(new EmotiModel(64 , "（*´▽｀*）"));
            emotiModels.add(new EmotiModel(65 , "（´・｀ ）♡"));
            emotiModels.add(new EmotiModel(66 , "（´ω｀♡%）"));
            emotiModels.add(new EmotiModel(67 , "♥(ˆ⌣ˆԅ)"));
            emotiModels.add(new EmotiModel(68 , "꒰˘̩̩̩⌣˘̩̩̩๑꒱♡"));
            emotiModels.add(new EmotiModel(69 , "ლ(́◉◞౪◟◉‵ლ)"));
            emotiModels.add(new EmotiModel(70 , "⸌̷̻( ᷇ॢ〰ॢ ᷆◍)⸌̷̻♡⃛"));
            emotiModels.add(new EmotiModel(71 , "₍՞◌′ᵕ‵ू◌₎♡"));
            emotiModels.add(new EmotiModel(72 , "♡ฅ(ᐤˊ꒳ฅˋᐤ♪)"));
            emotiModels.add(new EmotiModel(73 , "ʚ♡⃛ɞ(ू•ᴗ•ू❁)"));
            emotiModels.add(new EmotiModel(74 , "❣⃛(❛ั◡˜๑)"));
            emotiModels.add(new EmotiModel(75 , "( ˭̵̵̵̵͈́◡ु͂˭̵̵̵͈̀ )ˉ̞̭♡"));
            emotiModels.add(new EmotiModel(76 , "♡(ŐωŐ人)"));
            emotiModels.add(new EmotiModel(77 , "❤⃛ヾ(๑❛ ▿ ◠๑ )"));
            emotiModels.add(new EmotiModel(78 , "（*’∀’人）♥"));
            emotiModels.add(new EmotiModel(79 , "(°◡°♡).:｡"));
            emotiModels.add(new EmotiModel(80 , "ʸ(➜◡ु⚈᷉)♡⃛"));
            emotiModels.add(new EmotiModel(81 , "ˉ̞̭(′͈∨‵͈♡)˄̻ ̊"));
            emotiModels.add(new EmotiModel(82 , "◟(◔ั₀◔ั )◞ ༘♡"));
            emotiModels.add(new EmotiModel(83 , "φ(ﾟ ωﾟ//）♡"));
            emotiModels.add(new EmotiModel(84 , "ʸ(ᴖ́◡ु⚈᷉)♡⃛"));
            emotiModels.add(new EmotiModel(85 , "ꉂ (′̤ॢ∀ ू‵̤๑))ˉ̞̭♡"));
            emotiModels.add(new EmotiModel(86 , "♡♡+.ﾟ(￫ε￩*)ﾟ+.ﾟ"));
            emotiModels.add(new EmotiModel(87 , "꒰✪ૢꇵ✪ૢ꒱ෆ⃛"));
            emotiModels.add(new EmotiModel(88 , "(●´□`)♡"));
            emotiModels.add(new EmotiModel(89 , "(｡･ω･｡)ﾉ♡"));
            emotiModels.add(new EmotiModel(90 , "(｡’▽’｡)♡"));
            emotiModels.add(new EmotiModel(91 , "（●´∀｀）ノ♡"));
            emotiModels.add(new EmotiModel(92 , "₍₍ ( ๑॔˃̶◡ ˂̶๑॓)◞♡"));
            emotiModels.add(new EmotiModel(93 , "(๑・ω-)～♥”"));
            emotiModels.add(new EmotiModel(94 , "(๑°꒵°๑)･*♡"));
            emotiModels.add(new EmotiModel(95 , "～(^з^)-♡"));
            emotiModels.add(new EmotiModel(96 , "(๑ˊ͈ ॢꇴ ˋ͈)〜♡॰ॱ"));
            emotiModels.add(new EmotiModel(97, "(ෆ ͒•∘̬• ͒)◞"));
            emotiModels.add(new EmotiModel(98, "♡(㋭ ਊ ㋲)♡"));
            emotiModels.add(new EmotiModel(99, "( •ॢ◡-ॢ)-♡"));
            emotiModels.add(new EmotiModel(100, "(●’ᴗ’σ)σணღ*")); }
        else if (i == 1) {
            getSupportActionBar().setTitle("Happy");
            emotiModels.add(new EmotiModel(101, "(◕‿◕✿)"));
            emotiModels.add(new EmotiModel(102, "(◠‿◠✿)"));
            emotiModels.add(new EmotiModel(103, "(◠﹏◠✿)"));
            emotiModels.add(new EmotiModel(104, "（＊＾Ｕ＾）人（≧Ｖ≦＊）/"));
            emotiModels.add(new EmotiModel(105, "ôヮô"));
            emotiModels.add(new EmotiModel(106, "∧( ‘Θ’ )∧"));
            emotiModels.add(new EmotiModel(107, "(¤﹏¤)"));
            emotiModels.add(new EmotiModel(108, "●‿●"));
            emotiModels.add(new EmotiModel(109, "ʕ·ᴥ·ʔ"));
            emotiModels.add(new EmotiModel(110, "＼（＾○＾）人（＾○＾）／"));
            emotiModels.add(new EmotiModel(111, "ヾ(＠⌒▽⌒＠)ﾉ"));
            emotiModels.add(new EmotiModel(112, "(°∀°)"));
            emotiModels.add(new EmotiModel(113, "ヾ｜￣ー￣｜ﾉ"));
            emotiModels.add(new EmotiModel(114, "(☉‿☉✿)"));
            emotiModels.add(new EmotiModel(115, "┏(＾0＾)┛┗(＾0＾) ┓"));
            emotiModels.add(new EmotiModel(116, "(◡‿◡✿)"));
            emotiModels.add(new EmotiModel(117, "✿◕ ‿ ◕✿"));
            emotiModels.add(new EmotiModel(118, "ヽ(‘ ∇‘ )ノ"));
            emotiModels.add(new EmotiModel(119, "☆(❁‿❁)☆"));
            emotiModels.add(new EmotiModel(120, "❀◕ ‿ ◕❀"));
            emotiModels.add(new EmotiModel(121, "ヽ(^◇^*)/"));
            emotiModels.add(new EmotiModel(122, "(•⊙ω⊙•)"));
            emotiModels.add(new EmotiModel(123, "!⑈ˆ~ˆ!⑈"));
            emotiModels.add(new EmotiModel(124, "(*^ -^*)"));
            emotiModels.add(new EmotiModel(125, "(⊙‿⊙✿)"));
            emotiModels.add(new EmotiModel(126, "◕3◕"));
            emotiModels.add(new EmotiModel(127, "(ﾟヮﾟ)"));
            emotiModels.add(new EmotiModel(128, "¢‿¢"));
            emotiModels.add(new EmotiModel(129, "ヅ"));
            emotiModels.add(new EmotiModel(130, "●ᴥ●"));
            emotiModels.add(new EmotiModel(131, "(∪ ◡ ∪)"));
            emotiModels.add(new EmotiModel(132, "≖‿≖"));
            emotiModels.add(new EmotiModel(133, "≧◡≦"));
            emotiModels.add(new EmotiModel(134, "٩◔‿◔۶"));
            emotiModels.add(new EmotiModel(135, "｡◕ ‿ ◕｡"));
            emotiModels.add(new EmotiModel(136, "ヾ(＠＾▽＾＠)ﾉ"));
            emotiModels.add(new EmotiModel(137, "◃┆◉◡◉┆▷"));
            emotiModels.add(new EmotiModel(138, "(✿◠‿◠)"));
            emotiModels.add(new EmotiModel(139, "(￣ｰ￣)"));
            emotiModels.add(new EmotiModel(140, "╰(◡‿◡✿╰)"));
            emotiModels.add(new EmotiModel(141, "~,~"));
            emotiModels.add(new EmotiModel(142, "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧"));
            emotiModels.add(new EmotiModel(143, "(*~▽~)"));
            emotiModels.add(new EmotiModel(144, "❀‿❀"));
            emotiModels.add(new EmotiModel(145, "◕‿◕"));
            emotiModels.add(new EmotiModel(146, "(^L^)"));
            emotiModels.add(new EmotiModel(147, "(^▽^)"));
            emotiModels.add(new EmotiModel(148, "◕ ◡ ◕"));
            emotiModels.add(new EmotiModel(149, "(◕‿◕✿)"));
            emotiModels.add(new EmotiModel(150, "（ ；´Д｀）"));
            emotiModels.add(new EmotiModel(151, "⊙﹏⊙"));
            emotiModels.add(new EmotiModel(152, "✿｡✿"));
            emotiModels.add(new EmotiModel(153, "ヽ(゜∇゜)ノ"));
            emotiModels.add(new EmotiModel(154, "｡(✿‿✿)｡"));
            emotiModels.add(new EmotiModel(155, "(´ー｀)"));
            emotiModels.add(new EmotiModel(156, "ツ"));
            emotiModels.add(new EmotiModel(157, "q(❂‿❂)p"));
            emotiModels.add(new EmotiModel(158, "( ́ ◕◞ε◟◕`)"));
            emotiModels.add(new EmotiModel(159, "☆(◒‿◒)☆"));
            emotiModels.add(new EmotiModel(160, "(∩▂∩)"));
            emotiModels.add(new EmotiModel(161, "(¬‿¬)"));
            emotiModels.add(new EmotiModel(162, "(^Ｏ^)"));
            emotiModels.add(new EmotiModel(163, "ʘ‿ʘ"));
            emotiModels.add(new EmotiModel(164, "（’◎’）"));
            emotiModels.add(new EmotiModel(165, "(◜௰◝)"));
            emotiModels.add(new EmotiModel(166, "(^ｰ^)"));
            emotiModels.add(new EmotiModel(167, "(o´ω｀o)"));
            emotiModels.add(new EmotiModel(168, "(^з^)-☆"));
            emotiModels.add(new EmotiModel(169, "(◕ω◕✿)"));
            emotiModels.add(new EmotiModel(170, "(づ｡◕‿‿◕｡)づ"));
            emotiModels.add(new EmotiModel(171, "(ﾟ▽^*)"));
            emotiModels.add(new EmotiModel(172, "(⌒o⌒)"));
            emotiModels.add(new EmotiModel(173, "(｡◕‿◕｡)"));
            emotiModels.add(new EmotiModel(174, "ت"));
            emotiModels.add(new EmotiModel(175, "(. ﾟーﾟ)"));
            emotiModels.add(new EmotiModel(176, "१✌˚◡˚✌५"));
            emotiModels.add(new EmotiModel(177, "＼(●~▽~●)"));
            emotiModels.add(new EmotiModel(178, "(*˘︶˘*)"));
            emotiModels.add(new EmotiModel(179, "(✪㉨✪)"));
            emotiModels.add(new EmotiModel(180, "(ᅌᴗᅌ* )"));
            emotiModels.add(new EmotiModel(181, "^L^"));
            emotiModels.add(new EmotiModel(182, "(･ｪ-)"));
            emotiModels.add(new EmotiModel(183, "＼(*^▽^*)/"));
            emotiModels.add(new EmotiModel(184, "(◠△◠✿)"));
            emotiModels.add(new EmotiModel(185, "( ಠ◡ಠ )"));
            emotiModels.add(new EmotiModel(186, "(〃^∇^)ﾉ"));
            emotiModels.add(new EmotiModel(187, "^^"));
            emotiModels.add(new EmotiModel(188, "|◔◡◉|"));
            emotiModels.add(new EmotiModel(189, "(●⌒∇⌒●)"));
            emotiModels.add(new EmotiModel(190, "⊂◉‿◉つ"));
            emotiModels.add(new EmotiModel(191, ".ʕʘ‿ʘʔ."));
            emotiModels.add(new EmotiModel(192, "(*・∀・*)人(*・∀・*)"));
            emotiModels.add(new EmotiModel(193, "＼(^-^)／"));
            emotiModels.add(new EmotiModel(194, "∩(︶▽︶)∩"));
            emotiModels.add(new EmotiModel(195, "（☉∀☉）"));
            emotiModels.add(new EmotiModel(196, "(´ω｀)"));
            emotiModels.add(new EmotiModel(197, "●﹏●"));
            emotiModels.add(new EmotiModel(198, "（ ´∀｀）☆"));
            emotiModels.add(new EmotiModel(199, "•ᴥ•"));
            emotiModels.add(new EmotiModel(200, "✿◕ ‿ ◕✿")); }
        else if (i == 2) {
            getSupportActionBar().setTitle("Music");
            emotiModels.add(new EmotiModel(201, "ヾ(´〇`)ﾉ♪♪♪"));
            emotiModels.add(new EmotiModel(202, "ヘ(￣ω￣ヘ)"));
            emotiModels.add(new EmotiModel(203, "(〜￣▽￣)〜"));
            emotiModels.add(new EmotiModel(204, "〜(￣▽￣〜)"));
            emotiModels.add(new EmotiModel(205, "ヽ(o´∀`)ﾉ♪♬"));
            emotiModels.add(new EmotiModel(206, "(ﾉ≧∀≦)ﾉ"));
            emotiModels.add(new EmotiModel(207, "♪ヽ(^^ヽ)♪"));
            emotiModels.add(new EmotiModel(208, "♪(/_ _ )/♪"));
            emotiModels.add(new EmotiModel(209, "♪♬((d⌒ω⌒b))♬♪"));
            emotiModels.add(new EmotiModel(210, "└(￣-￣└))"));
            emotiModels.add(new EmotiModel(211, "((┘￣ω￣)┘"));
            emotiModels.add(new EmotiModel(212, "√(￣‥￣√)"));
            emotiModels.add(new EmotiModel(213, "└(＾＾)┐"));
            emotiModels.add(new EmotiModel(214, "┌(＾＾)┘"));
            emotiModels.add(new EmotiModel(215, "＼(￣▽￣)＼"));
            emotiModels.add(new EmotiModel(216, "／(￣▽￣)／"));
            emotiModels.add(new EmotiModel(217, "(￣▽￣)/♫•*¨*•.¸¸♪"));
            emotiModels.add(new EmotiModel(218, "(^_^♪)"));
            emotiModels.add(new EmotiModel(219, "(~˘▽˘)~"));
            emotiModels.add(new EmotiModel(220, "~(˘▽˘~)"));
            emotiModels.add(new EmotiModel(221, "ヾ(⌐■_■)ノ♪"));
            emotiModels.add(new EmotiModel(222, "(〜￣△￣)〜"));
            emotiModels.add(new EmotiModel(223, "(~‾▽‾)~"));
            emotiModels.add(new EmotiModel(224, "~(˘▽˘)~"));
            emotiModels.add(new EmotiModel(225, "乁( • ω •乁)"));
            emotiModels.add(new EmotiModel(226, "(｢• ω •)｢"));
            emotiModels.add(new EmotiModel(227, "⁽⁽◝( • ω • )◜⁾⁾"));
            emotiModels.add(new EmotiModel(228, "✺◟( • ω • )◞✺"));
            emotiModels.add(new EmotiModel(229, "♬♫♪◖(● o ●)◗♪♫♬"));
            emotiModels.add(new EmotiModel(230, "( ˘ ɜ˘) ♬♪♫"));
            emotiModels.add(new EmotiModel(231, "♪♪♪ ヽ(ˇ∀ˇ )ゞ"));
            emotiModels.add(new EmotiModel(232, "(o・★)"));
            emotiModels.add(new EmotiModel(233, "(☆￢o)q"));
            emotiModels.add(new EmotiModel(234, "(^_^♪)"));
            emotiModels.add(new EmotiModel(235, "(´△｀)♪"));
            emotiModels.add(new EmotiModel(236, "ρ(o＜★)"));
            emotiModels.add(new EmotiModel(237, "ρ(o＾★)"));
            emotiModels.add(new EmotiModel(238, "(☆￣o)q"));
            emotiModels.add(new EmotiModel(239, "(☆∩o)q"));
            emotiModels.add(new EmotiModel(240, "(☆≧o)q"));
            emotiModels.add(new EmotiModel(241, "(☆Θo)q"));
            emotiModels.add(new EmotiModel(242, "(´0｀)q"));
            emotiModels.add(new EmotiModel(243, "ρ(oμ★)"));
            emotiModels.add(new EmotiModel(244, "（＾Ｏ＾☆♪"));
            emotiModels.add(new EmotiModel(245, "（＾3＾）~♪"));
            emotiModels.add(new EmotiModel(246, "（*´▽｀*）"));
            emotiModels.add(new EmotiModel(247, "ρ（ーoー)♪"));
            emotiModels.add(new EmotiModel(248, "（^Ｏ^）～♪"));
            emotiModels.add(new EmotiModel(249, "ρ(o δ★)"));
            emotiModels.add(new EmotiModel(250, "ρ(＾o^)♪"));
            emotiModels.add(new EmotiModel(251, "ρ（^o^）♪"));
            emotiModels.add(new EmotiModel(252, "ρ（＾o＾）♪"));
            emotiModels.add(new EmotiModel(253, "♫꒰･◡･๑꒱"));
            emotiModels.add(new EmotiModel(254, "(o^^o)♪"));
            emotiModels.add(new EmotiModel(255, "♫♪˙‿˙♫♪"));
            emotiModels.add(new EmotiModel(256, "♪(ﾉε｀●)"));
            emotiModels.add(new EmotiModel(257, "ρ(^^ )♭"));
            emotiModels.add(new EmotiModel(258, "♪～(￣ε￣)"));
            emotiModels.add(new EmotiModel(259, "♪(´ε｀ )"));
            emotiModels.add(new EmotiModel(260, "（＊＾ω＾）♪"));
            emotiModels.add(new EmotiModel(261, "≧(´▽｀)≦"));        }
        else if (i == 3) {
            getSupportActionBar().setTitle("Animals");
            emotiModels.add(new EmotiModel(262, "(^^ゞ"));
            emotiModels.add(new EmotiModel(263, "(〃▽〃)"));
            emotiModels.add(new EmotiModel(264, "(ノ▽〃)"));
            emotiModels.add(new EmotiModel(265, "（/｡＼)"));
            emotiModels.add(new EmotiModel(266, "(/ω＼)"));
            emotiModels.add(new EmotiModel(267, "(Ŏ艸Ŏ)"));
            emotiModels.add(new EmotiModel(268, "(^^;)"));
            emotiModels.add(new EmotiModel(269, "(〃ー〃)"));
            emotiModels.add(new EmotiModel(270, "(〃ω〃)"));
            emotiModels.add(new EmotiModel(271, "(〃艸〃)"));
            emotiModels.add(new EmotiModel(272, "(´つヮ⊂)"));
            emotiModels.add(new EmotiModel(273, "(♡´艸`)"));
            emotiModels.add(new EmotiModel(274, "(／≧ω＼)"));
            emotiModels.add(new EmotiModel(275, "ʕ*ﾉᴥﾉʔ"));
            emotiModels.add(new EmotiModel(276, "(/へ＼*)"));
            emotiModels.add(new EmotiModel(277, "(*ﾉ▽ﾉ)"));
            emotiModels.add(new EmotiModel(278, "(*ﾉωﾉ)"));
            emotiModels.add(new EmotiModel(279, "(*ﾉдﾉ)"));
            emotiModels.add(new EmotiModel(280, "(´～｀ヾ)"));
            emotiModels.add(new EmotiModel(281, "(ﾉ∇≦*)"));
            emotiModels.add(new EmotiModel(282, "(‘-’*)"));
            emotiModels.add(new EmotiModel(283, "(^◇^；)"));
            emotiModels.add(new EmotiModel(284, "|▽//)ゝ"));
            emotiModels.add(new EmotiModel(285, "(〃´∀｀)"));
            emotiModels.add(new EmotiModel(286, "ꈍ .̮ ꈍ"));
            emotiModels.add(new EmotiModel(287, "(〃∀〃)ゞ"));
            emotiModels.add(new EmotiModel(288, "( 〃．．)"));
            emotiModels.add(new EmotiModel(289, "(｡･･｡)"));
            emotiModels.add(new EmotiModel(290, "|´∀｀●)"));
            emotiModels.add(new EmotiModel(291, "((-ω-｡)(｡-ω-))"));
            emotiModels.add(new EmotiModel(292, "ＯＴＬ"));
            emotiModels.add(new EmotiModel(293, "ｏｒｚ"));
            emotiModels.add(new EmotiModel(294, "＿ﾉフ○"));
            emotiModels.add(new EmotiModel(295, "(￣Д￣"));
            emotiModels.add(new EmotiModel(296, "(´Д⊂"));
            emotiModels.add(new EmotiModel(297, "（－－；"));
            emotiModels.add(new EmotiModel(298, "（´。｀)"));
            emotiModels.add(new EmotiModel(299, "（￣Ω￣）"));
            emotiModels.add(new EmotiModel(300, "(A´Å｀"));
            emotiModels.add(new EmotiModel(301, "A^-^)"));
            emotiModels.add(new EmotiModel(302, "(∋д∈)"));
            emotiModels.add(new EmotiModel(303, "(・。-;"));
            emotiModels.add(new EmotiModel(304, "（´・｀）"));
            emotiModels.add(new EmotiModel(305, "(*Q*)"));
            emotiModels.add(new EmotiModel(306, "(／０￣)"));
            emotiModels.add(new EmotiModel(307, "＿|￣|○"));
            emotiModels.add(new EmotiModel(308, "(-。-;"));
            emotiModels.add(new EmotiModel(309, "(´Д｀)"));
            emotiModels.add(new EmotiModel(310, "(;´Д｀)"));
            emotiModels.add(new EmotiModel(311, "（＾。＾；）"));
            emotiModels.add(new EmotiModel(312, "(≧∀≦ゞ"));
            emotiModels.add(new EmotiModel(313, "(-ω-ゞ"));
            emotiModels.add(new EmotiModel(314, "(≧ω≦)ゞ"));
            emotiModels.add(new EmotiModel(315, "(｀-´)>"));
            emotiModels.add(new EmotiModel(316, "∠(｀∪´)"));
            emotiModels.add(new EmotiModel(317, "|`Д´)＞"));
            emotiModels.add(new EmotiModel(318, "(≧∇≦)b"));
            emotiModels.add(new EmotiModel(319, "(・∀-d)"));
            emotiModels.add(new EmotiModel(320, "(`Д´)ゞ"));
            emotiModels.add(new EmotiModel(321, "|▼皿▼)b"));
            emotiModels.add(new EmotiModel(322, "(・∧‐)ゞ"));
            emotiModels.add(new EmotiModel(323, "(●・ω・)b"));
            emotiModels.add(new EmotiModel(324, "ｄ(´▽｀*)"));
            emotiModels.add(new EmotiModel(325, "(*゜－＾)ゞ"));
            emotiModels.add(new EmotiModel(326, "(°∀°)ゝ”"));
            emotiModels.add(new EmotiModel(327, "(*｀Ω´)b"));
            emotiModels.add(new EmotiModel(328, "(＞Д＜)ゝ”"));
            emotiModels.add(new EmotiModel(329, "(=ﾟ▽ﾟ)/"));
            emotiModels.add(new EmotiModel(330, "('∀`)ゝ”"));
            emotiModels.add(new EmotiModel(331, "( ｀д´)b"));
            emotiModels.add(new EmotiModel(332, "d(￣▽￣o)"));
            emotiModels.add(new EmotiModel(333, "(*>ω<)b"));
            emotiModels.add(new EmotiModel(334, "(｀∀´)ゝ”"));
            emotiModels.add(new EmotiModel(335, "d(´･ω･`)"));
            emotiModels.add(new EmotiModel(336, "(*´ω｀*)ノ"));
            emotiModels.add(new EmotiModel(337, "(★´ω｀★)ゞ"));
            emotiModels.add(new EmotiModel(338, "(●´･∀･)b"));
            emotiModels.add(new EmotiModel(339, "d(*ﾟーﾟ*)"));
            emotiModels.add(new EmotiModel(340, "☆(･ω･*)ゞ"));
            emotiModels.add(new EmotiModel(341, "(●⌒∇⌒●)b"));
            emotiModels.add(new EmotiModel(342, "((´д｀))"));
            emotiModels.add(new EmotiModel(343, "((；ﾟДﾟ)"));
            emotiModels.add(new EmotiModel(344, "((;ﾟДﾟ))"));
            emotiModels.add(new EmotiModel(345, "(llФｗФ｀)"));
            emotiModels.add(new EmotiModel(346, "((ﾟДﾟ；))"));
            emotiModels.add(new EmotiModel(347, "((；ﾟェﾟ；))"));
            emotiModels.add(new EmotiModel(348, ":(´◦ω◦｀):"));
            emotiModels.add(new EmotiModel(349, "(((＾ω＾)))"));
            emotiModels.add(new EmotiModel(350, "（（（゜Д゜；）））"));
            emotiModels.add(new EmotiModel(351, "（（（・×・；）））"));
            emotiModels.add(new EmotiModel(352, "(((･Α･川)))"));
            emotiModels.add(new EmotiModel(353, "((( ；ﾟДﾟ)))"));
            emotiModels.add(new EmotiModel(354, "((,,´Θ`,,))"));
            emotiModels.add(new EmotiModel(355, "((o(´∀｀)o))"));
            emotiModels.add(new EmotiModel(356, "《《(ﾟc_ﾟ；)》》"));
            emotiModels.add(new EmotiModel(357, ":;(∩´﹏`∩);:"));
            emotiModels.add(new EmotiModel(358, "((((；ﾟДﾟ)))"));
            emotiModels.add(new EmotiModel(359, "||lll´Д｀)))"));
            emotiModels.add(new EmotiModel(360, "((((；ﾟДﾟ))))"));
            emotiModels.add(new EmotiModel(361, "((ﾟﾟ((Д))ﾟﾟ))"));        }
        else if (i == 4) {
            getSupportActionBar().setTitle("Angry");
            emotiModels.add(new EmotiModel(362, "凸(｀0´)凸"));
            emotiModels.add(new EmotiModel(363, "凸ಠ益ಠ)凸"));
            emotiModels.add(new EmotiModel(364, "凸(⊙▂⊙✖ )"));
            emotiModels.add(new EmotiModel(365, "┌П┐(►˛◄’!)"));
            emotiModels.add(new EmotiModel(366, "凸(-0-メ)"));
            emotiModels.add(new EmotiModel(367, "凸(｀⌒´メ)凸"));
            emotiModels.add(new EmotiModel(368, "凸(｀△´＋）"));
            emotiModels.add(new EmotiModel(369, "( ︶︿︶)_╭∩╮"));
            emotiModels.add(new EmotiModel(370, "凸(｀ι _´メ）"));
            emotiModels.add(new EmotiModel(371, "凸(>皿<)凸"));
            emotiModels.add(new EmotiModel(372, "凸(^▼ｪ▼ﾒ^)"));
            emotiModels.add(new EmotiModel(373, "t(=n=)"));
            emotiModels.add(new EmotiModel(374, "t(- n -)t"));
            emotiModels.add(new EmotiModel(375, "凸(¬‿¬)"));
            emotiModels.add(new EmotiModel(376, "┌∩┐(◣_◢)┌∩┐"));
            emotiModels.add(new EmotiModel(377, "┌∩┐(ಠ_ಠ)┌∩┐"));
            emotiModels.add(new EmotiModel(378, "╭∩╮(︶︿︶)╭∩╮"));
            emotiModels.add(new EmotiModel(379, "╭∩╮(-_-)╭∩╮"));
            emotiModels.add(new EmotiModel(380, "( ≧Д≦)"));
            emotiModels.add(new EmotiModel(381, "(；￣Д￣）"));
            emotiModels.add(new EmotiModel(382, "(;¬_¬)"));
            emotiModels.add(new EmotiModel(383, "（；¬＿¬)"));
            emotiModels.add(new EmotiModel(384, "(｡+･`ω･´)"));
            emotiModels.add(new EmotiModel(385, "｡゜(｀Д´)゜｡"));
            emotiModels.add(new EmotiModel(386, "(　ﾟДﾟ)＜!!"));
            emotiModels.add(new EmotiModel(387, "(‡▼益▼)"));
            emotiModels.add(new EmotiModel(388, "(,,#ﾟДﾟ)"));
            emotiModels.add(new EmotiModel(389, "(҂⌣̀_⌣́)"));
            emotiModels.add(new EmotiModel(390, "(；¬д¬)"));
            emotiModels.add(new EmotiModel(391, "（;≧皿≦）"));
            emotiModels.add(new EmotiModel(392, "(╬ﾟ◥益◤ﾟ)"));
            emotiModels.add(new EmotiModel(393, "(╬⓪益⓪)"));
            emotiModels.add(new EmotiModel(394, "[○･｀Д´･○]"));
            emotiModels.add(new EmotiModel(395, "૮( ᵒ̌▱๋ᵒ̌ )ა"));
            emotiModels.add(new EmotiModel(396, "(⁎˃ᆺ˂)"));
            emotiModels.add(new EmotiModel(397, "(ꐦ°᷄д°᷅)"));
            emotiModels.add(new EmotiModel(398, "((╬●∀●)"));
            emotiModels.add(new EmotiModel(399, "(╬ Ò ‸ Ó)"));
            emotiModels.add(new EmotiModel(400, "( >д<)"));
            emotiModels.add(new EmotiModel(401, "(*｀益´*)"));
            emotiModels.add(new EmotiModel(402, "(☞◣д◢)☞"));
            emotiModels.add(new EmotiModel(403, "<(｀^´)>"));
            emotiModels.add(new EmotiModel(404, "(;｀O´)o"));
            emotiModels.add(new EmotiModel(405, "(ꐦ ಠ皿ಠ )"));
            emotiModels.add(new EmotiModel(406, "（｀Δ´）！"));
            emotiModels.add(new EmotiModel(407, "(*｀Ω´*)"));
            emotiModels.add(new EmotiModel(408, "(╬ಠ益ಠ)"));
            emotiModels.add(new EmotiModel(409, "(╬ﾟ◥益◤ﾟ) ╬ﾟ"));
            emotiModels.add(new EmotiModel(410, "(ு⁎ு)྆྆"));
            emotiModels.add(new EmotiModel(411, "(╬⓪益⓪)"));
            emotiModels.add(new EmotiModel(412, "（╬ಠ益ಠ)"));
            emotiModels.add(new EmotiModel(413, "(●o≧д≦)o"));
            emotiModels.add(new EmotiModel(414, "=͟͟͞͞( •̀д•́)))"));
            emotiModels.add(new EmotiModel(415, "(๑･`▱´･๑)"));
            emotiModels.add(new EmotiModel(416, "༼ つ ͠° ͟ ͟ʖ ͡° ༽つ"));
            emotiModels.add(new EmotiModel(417, "(☄ฺ◣д◢)☄ฺ"));
            emotiModels.add(new EmotiModel(418, "ꀯ(‴ꑒ᷅⺫ꑒ᷄)"));
            emotiModels.add(new EmotiModel(419, "(#｀皿´)"));
            emotiModels.add(new EmotiModel(420, "(｀Д´)"));
            emotiModels.add(new EmotiModel(421, "(ﾒﾟ皿ﾟ)"));
            emotiModels.add(new EmotiModel(422, "(o｀ﾟ皿ﾟ)"));
            emotiModels.add(new EmotiModel(423, "( ╬◣ 益◢)"));
            emotiModels.add(new EmotiModel(424, "（╬ಠ益ಠ)"));
            emotiModels.add(new EmotiModel(425, "（♯▼皿▼）"));
            emotiModels.add(new EmotiModel(426, "( ╬◣ 益◢）y━･~"));
            emotiModels.add(new EmotiModel(427, "（○｀Ｏ´○）"));
            emotiModels.add(new EmotiModel(428, "(; ･`д･´)"));
            emotiModels.add(new EmotiModel(429, "｜。｀＞Д＜｜"));
            emotiModels.add(new EmotiModel(430, "(; ･`д･´)​"));
            emotiModels.add(new EmotiModel(431, "( •̀ω•́ )σ"));
            emotiModels.add(new EmotiModel(432, "o(-`д´- ｡)"));
            emotiModels.add(new EmotiModel(433, "(´･益･｀*)"));
            emotiModels.add(new EmotiModel(434, "(´Д｀)"));
            emotiModels.add(new EmotiModel(435, "(¬д¬。)"));
            emotiModels.add(new EmotiModel(436, "（≧▼≦；)"));
            emotiModels.add(new EmotiModel(437, "(ᇂ∀ᇂ╬)"));
            emotiModels.add(new EmotiModel(438, "(ू˃̣̣̣̣̣̣︿˂̣̣̣̣̣̣ ू)"));
            emotiModels.add(new EmotiModel(439, "(ू˃̣̣̣̣̣̣o˂̣̣̣̣̣̣ ू)⁼³₌₃"));
            emotiModels.add(new EmotiModel(440, "（▼へ▼メ）"));
            emotiModels.add(new EmotiModel(441, "｢(#Φ益 Φo)∩"));
            emotiModels.add(new EmotiModel(442, "s(・｀ヘ´・；)"));
            emotiModels.add(new EmotiModel(443, "s(・｀ヘ´・;)ゞ"));
            emotiModels.add(new EmotiModel(444, "Σ(-`Д´-ﾉ；)ﾉ"));
            emotiModels.add(new EmotiModel(445, "Σ(▼□▼メ)"));
            emotiModels.add(new EmotiModel(446, "๛∙᷅῞ॄ∙᷄"));
            emotiModels.add(new EmotiModel(447, "(°ㅂ° ╬)"));
            emotiModels.add(new EmotiModel(448, "( ｰ̀εｰ́ )"));
            emotiModels.add(new EmotiModel(449, "(눈_눈)"));
            emotiModels.add(new EmotiModel(450, "(´◣д◢`+)"));
            emotiModels.add(new EmotiModel(451, "(ʘ言ʘ╬)"));
            emotiModels.add(new EmotiModel(452, "(Ò 皿 Ó ╬)"));
            emotiModels.add(new EmotiModel(453, "(-̀◞८̯◟-́)"));
            emotiModels.add(new EmotiModel(454, "( ͒˃⌂˂ ͒)"));
            emotiModels.add(new EmotiModel(455, "┌(▀Ĺ̯ ▀-͠ )┐"));
            emotiModels.add(new EmotiModel(456, "[⑇⨀ེ⌓⨀ེ•⑇]"));
            emotiModels.add(new EmotiModel(457, "Σ(ﾟд´;ﾉ)ﾉ"));
            emotiModels.add(new EmotiModel(458, "(-̀◞▥◟-́)"));
            emotiModels.add(new EmotiModel(459, "☜(`o´)"));
            emotiModels.add(new EmotiModel(460, "(◎益◎;)"));
            emotiModels.add(new EmotiModel(461, "(@益@ .:;)"));        }
        else if (i == 5) {
            getSupportActionBar().setTitle("Sad");
            emotiModels.add(new EmotiModel(462, "ಥ_ಥ"));
            emotiModels.add(new EmotiModel(463, "(-’๏_๏’-)"));
            emotiModels.add(new EmotiModel(464, "˚⌇˚"));
            emotiModels.add(new EmotiModel(465, "o(╥﹏╥)o"));
            emotiModels.add(new EmotiModel(466, "(⊙﹏⊙✿)"));
            emotiModels.add(new EmotiModel(467, "●︿●"));
            emotiModels.add(new EmotiModel(468, "(一。一;;）"));
            emotiModels.add(new EmotiModel(469, "(╯︵╰,)"));
            emotiModels.add(new EmotiModel(470, "(︶︹︺)"));
            emotiModels.add(new EmotiModel(471, "(◡﹏◡✿)"));
            emotiModels.add(new EmotiModel(472, "(✖﹏✖)"));
            emotiModels.add(new EmotiModel(473, "‘︿’"));
            emotiModels.add(new EmotiModel(474, "v( ‘.’ )v"));
            emotiModels.add(new EmotiModel(475, "◄.►"));
            emotiModels.add(new EmotiModel(476, "(ㄒoㄒ)"));
            emotiModels.add(new EmotiModel(477, "⊙︿⊙"));
            emotiModels.add(new EmotiModel(478, "(◕︿◕✿)"));
            emotiModels.add(new EmotiModel(479, "ਉ_ਉ"));
            emotiModels.add(new EmotiModel(480, "┐(‘～`；)┌"));
            emotiModels.add(new EmotiModel(481, "(︶︹︺)"));
            emotiModels.add(new EmotiModel(482, "흫_흫"));
            emotiModels.add(new EmotiModel(483, "ب_ب"));
            emotiModels.add(new EmotiModel(484, "╮(─▽─)╭"));
            emotiModels.add(new EmotiModel(485, "ಥ‿ಥ"));
            emotiModels.add(new EmotiModel(486, "(-’_’-)"));
            emotiModels.add(new EmotiModel(487, "(╥╥)"));
            emotiModels.add(new EmotiModel(488, "(•̪●)"));
            emotiModels.add(new EmotiModel(489, "(∩︵∩)"));
            emotiModels.add(new EmotiModel(490, "(o_-)"));
            emotiModels.add(new EmotiModel(491, "(｡-_-｡)"));
            emotiModels.add(new EmotiModel(492, "(╯_╰)"));
            emotiModels.add(new EmotiModel(493, "(╥_╥)"));
            emotiModels.add(new EmotiModel(494, "v(ಥ ̯ ಥ)v"));
            emotiModels.add(new EmotiModel(495, "<('.'<)"));
            emotiModels.add(new EmotiModel(496, "ಠ,ಥ"));
            emotiModels.add(new EmotiModel(497, "(◕︵◕)"));
            emotiModels.add(new EmotiModel(498, "(´ヘ｀()"));
            emotiModels.add(new EmotiModel(499, "(✖╭╮✖)"));
            emotiModels.add(new EmotiModel(500, "(◕﹏◕✿)"));
            emotiModels.add(new EmotiModel(501, "(+_+)"));
            emotiModels.add(new EmotiModel(502, "★~(◠︿◕✿)"));
            emotiModels.add(new EmotiModel(503, "(*´д｀*)"));
            emotiModels.add(new EmotiModel(504, "(◡△◡✿)"));
            emotiModels.add(new EmotiModel(505, "٩(×̯×)۶"));
            emotiModels.add(new EmotiModel(506, "(ノ_・。)"));
            emotiModels.add(new EmotiModel(507, "┐(‘～`；)┌"));
            emotiModels.add(new EmotiModel(508, "(つд｀)"));
            emotiModels.add(new EmotiModel(509, "(✖╭╮✖)"));
            emotiModels.add(new EmotiModel(510, "ಥ⌣ಥ"));
            emotiModels.add(new EmotiModel(511, "இ_இ"));
            emotiModels.add(new EmotiModel(512, "✖‿✖"));
            emotiModels.add(new EmotiModel(513, "( ≧Д≦)"));
            emotiModels.add(new EmotiModel(514, "((´д｀))"));
            emotiModels.add(new EmotiModel(515, "(∩︵∩)"));
            emotiModels.add(new EmotiModel(516, "(▰˘︹˘▰)"));
            emotiModels.add(new EmotiModel(517, "(✖╭╮✖)"));
            emotiModels.add(new EmotiModel(518, "(‘A`)"));
            emotiModels.add(new EmotiModel(519, "(︶︹︺)"));
            emotiModels.add(new EmotiModel(520, "(＠´＿｀＠)"));
            emotiModels.add(new EmotiModel(521, "（´＿｀）"));
            emotiModels.add(new EmotiModel(522, "(⊙︿⊙✿)"));
            emotiModels.add(new EmotiModel(523, "(⌣_⌣”)"));
            emotiModels.add(new EmotiModel(524, "(▰︶︹︺▰)"));
            emotiModels.add(new EmotiModel(525, "~(｡☉︵ ಠ@)>"));
            emotiModels.add(new EmotiModel(526, "⊙︿⊙"));
            emotiModels.add(new EmotiModel(527, "ヽ(●ﾟ´Д｀ﾟ●)ﾉﾟ"));
            emotiModels.add(new EmotiModel(528, "(.﹒︣︿﹒︣.)"));
            emotiModels.add(new EmotiModel(529, "(Θ︹Θ)ს"));
            emotiModels.add(new EmotiModel(530, "٩꒰´·⌢•｀꒱۶⁼³₌₃"));
            emotiModels.add(new EmotiModel(531, ":: ˓(ᑊᘩᑊ⁎) ::"));
            emotiModels.add(new EmotiModel(532, "˓˓(ᑊᘩᑊ⁎)"));
            emotiModels.add(new EmotiModel(533, "(๑◕︵◕๑)"));
            emotiModels.add(new EmotiModel(534, "( .. )"));
            emotiModels.add(new EmotiModel(535, "(｡•́︿•̀｡)"));
            emotiModels.add(new EmotiModel(536, "(´°ω°`)"));
            emotiModels.add(new EmotiModel(537, "੨( ･᷄ ︵･᷅ )ｼ"));
            emotiModels.add(new EmotiModel(538, "꒰๑˃͈꒳˂͈๑꒱ﾉ*ﾞ̥"));
            emotiModels.add(new EmotiModel(539, "(⌯˃̶᷄ ﹏ ˂̶᷄⌯)ﾟ"));
            emotiModels.add(new EmotiModel(540, "(っ- ‸ – ς)"));
            emotiModels.add(new EmotiModel(541, "(๑′°︿°๑)"));
            emotiModels.add(new EmotiModel(542, "⊛ठ̯⊛"));
            emotiModels.add(new EmotiModel(543, "ಠ╭╮ಠ"));
            emotiModels.add(new EmotiModel(544, "( ◞᷄દ◟᷅ )"));
            emotiModels.add(new EmotiModel(545, "(oꆤ︵ꆤo)"));
            emotiModels.add(new EmotiModel(546, "ಗಾ ﹏ ಗಾ"));
            emotiModels.add(new EmotiModel(547, "ᵟຶᴖ ᵟຶ"));
            emotiModels.add(new EmotiModel(548, "(⋅⃘˕̭⋅⃘)"));
            emotiModels.add(new EmotiModel(549, "ōۃō"));
            emotiModels.add(new EmotiModel(550, "( ⁍᷄⌢̻⁍᷅ )"));
            emotiModels.add(new EmotiModel(551, "(.﹒︠₋﹒︡.)"));
            emotiModels.add(new EmotiModel(552, "(˵¯͒⌢͗¯͒˵)"));
            emotiModels.add(new EmotiModel(553, "☹ै"));
            emotiModels.add(new EmotiModel(554, "(　´_ﾉ` )"));
            emotiModels.add(new EmotiModel(555, "ʕ ಡ ﹏ ಡ ʔ"));
            emotiModels.add(new EmotiModel(556, "●︿●"));
            emotiModels.add(new EmotiModel(557, "(◕︿◕✿)"));
            emotiModels.add(new EmotiModel(558, "ਉ_ਉ"));
            emotiModels.add(new EmotiModel(559, "༶ඬ༝ඬ༶"));
            emotiModels.add(new EmotiModel(560, "(;-_-)/"));
            emotiModels.add(new EmotiModel(561, "(oT-T)尸"));        }
        else if (i == 6) {
            getSupportActionBar().setTitle("Sleeping");
            emotiModels.add(new EmotiModel(562, "[(－－)]..zzZ"));
            emotiModels.add(new EmotiModel(563, "(－_－) zzZ"));
            emotiModels.add(new EmotiModel(564, "(∪｡∪)｡｡｡zzZ"));
            emotiModels.add(new EmotiModel(565, "(－ω－) zzZ"));
            emotiModels.add(new EmotiModel(566, "(￣o￣) zzZZzzZZ"));
            emotiModels.add(new EmotiModel(567, "(( _ _ ))..zzzZZ"));
            emotiModels.add(new EmotiModel(568, "(￣ρ￣)..zzZZ"));
            emotiModels.add(new EmotiModel(569, "(－.－)...zzz"));
            emotiModels.add(new EmotiModel(570, "(＿ ＿*) Z z z"));
            emotiModels.add(new EmotiModel(571, "(x . x) ~~zzZ"));
            emotiModels.add(new EmotiModel(572, "【:εω"));
            emotiModels.add(new EmotiModel(573, "(冫༵、)"));
            emotiModels.add(new EmotiModel(574, "(ᴗ˳ᴗ)"));
            emotiModels.add(new EmotiModel(575, "(´～`)"));
            emotiModels.add(new EmotiModel(576, "( ⓥωⓥ)"));
            emotiModels.add(new EmotiModel(577, "(:˒[￣]"));
            emotiModels.add(new EmotiModel(578, "(*-ω-)"));
            emotiModels.add(new EmotiModel(579, "(︶｡︶✽)"));
            emotiModels.add(new EmotiModel(580, "(:3ぅ　)"));
            emotiModels.add(new EmotiModel(581, "(¦ꒉ[▓▓]"));
            emotiModels.add(new EmotiModel(582, "(¦ꀦ[▓▓]"));
            emotiModels.add(new EmotiModel(583, "⌈▓͟⌉ꆟ)ꍞ"));
            emotiModels.add(new EmotiModel(584, "（;´_ヘ;）"));
            emotiModels.add(new EmotiModel(585, "（´○｀）～ゝ"));
            emotiModels.add(new EmotiModel(586, "(¦ꃎ[▓▓]"));
            emotiModels.add(new EmotiModel(587, "(¦ꎌ[▓▓]"));
            emotiModels.add(new EmotiModel(588, "(¦ꃆ[▓▓]"));
            emotiModels.add(new EmotiModel(589, "(¦ꄰ[▓▓]"));
            emotiModels.add(new EmotiModel(590, "⌈▒͟⌉ꅼ)ꍞ"));
            emotiModels.add(new EmotiModel(591, "＼（´Ｏ｀）／"));
            emotiModels.add(new EmotiModel(592, "（◎´〇｀◎）"));
            emotiModels.add(new EmotiModel(593, "(´-εヾ )"));
            emotiModels.add(new EmotiModel(594, "(｡し_し｡)"));
            emotiModels.add(new EmotiModel(595, "(｡´-д-)"));
            emotiModels.add(new EmotiModel(596, "(*´ο`*)"));
            emotiModels.add(new EmotiModel(597, "川｡μ_μ)σ"));
            emotiModels.add(new EmotiModel(598, "(｡v_v｡)"));
            emotiModels.add(new EmotiModel(599, "(๑ᵕ⌓ᵕ̤)"));
            emotiModels.add(new EmotiModel(600, "(¦ꃩ[▓▓]"));
            emotiModels.add(new EmotiModel(601, "꒰◍ᐡᐤᐡ◍꒱"));        }
        else if (i == 7) {
            getSupportActionBar().setTitle("Excited");
            emotiModels.add(new EmotiModel(602, "≧ω≦"));
            emotiModels.add(new EmotiModel(603, "୧⍢⃝୨"));
            emotiModels.add(new EmotiModel(604, "(⊙ᗜ⊙)"));
            emotiModels.add(new EmotiModel(605, "โ๏∀๏ใ"));
            emotiModels.add(new EmotiModel(606, "(≧∀≦)"));
            emotiModels.add(new EmotiModel(607, "۹⌤_⌤۹"));
            emotiModels.add(new EmotiModel(608, "୧☉□☉୨"));
            emotiModels.add(new EmotiModel(609, "(⊙ꇴ⊙)"));
            emotiModels.add(new EmotiModel(610, "(´∀`)"));
            emotiModels.add(new EmotiModel(611, "（・ｗ・）"));
            emotiModels.add(new EmotiModel(612, "(ᗒᗨᗕ)"));
            emotiModels.add(new EmotiModel(613, "ʘ ͜ʖ ʘ"));
            emotiModels.add(new EmotiModel(614, "(≧∇≦*)"));
            emotiModels.add(new EmotiModel(615, "(*≧▽≦)"));
            emotiModels.add(new EmotiModel(616, "۹(ÒہÓ)۶"));
            emotiModels.add(new EmotiModel(617, "(ﾉ･ｪ･)ﾉ"));
            emotiModels.add(new EmotiModel(618, "٩(^ᴗ^)۶"));
            emotiModels.add(new EmotiModel(619, "б（＞ε＜）∂"));
            emotiModels.add(new EmotiModel(620, "(⌬̀⌄⌬́)"));
            emotiModels.add(new EmotiModel(621, "٩(θ‿θ)۶"));
            emotiModels.add(new EmotiModel(622, "ヽ(＾Д＾)ﾉ"));
            emotiModels.add(new EmotiModel(623, "(★^O^★)"));
            emotiModels.add(new EmotiModel(624, "（๑✧∀✧๑）"));
            emotiModels.add(new EmotiModel(625, "(*≧∀≦*)"));
            emotiModels.add(new EmotiModel(626, "٩(●ᴗ●)۶"));
            emotiModels.add(new EmotiModel(627, "⸍⚙̥ꇴ⚙̥⸌"));
            emotiModels.add(new EmotiModel(628, "(๑>ᴗ<๑)"));
            emotiModels.add(new EmotiModel(629, "۹(˒௰˓)۶"));
            emotiModels.add(new EmotiModel(630, "(* >ω<)"));
            emotiModels.add(new EmotiModel(631, "＼（Ｔ∇Ｔ）／"));        }
        else if (i == 8) {
            getSupportActionBar().setTitle("Hungry");
            emotiModels = new ArrayList<>();
            emotiModels.add(new EmotiModel(632, "―●○◎-"));
            emotiModels.add(new EmotiModel(633, "―⊂ZZZ⊃"));
            emotiModels.add(new EmotiModel(634, "（￣ｗ￣）Ψ"));
            emotiModels.add(new EmotiModel(635, "◥█̆̈◤࿉∥"));
            emotiModels.add(new EmotiModel(636, "(＾-＾)＿日"));
            emotiModels.add(new EmotiModel(637, "(。・・)_且"));
            emotiModels.add(new EmotiModel(638, "(＃´ー´)旦"));
            emotiModels.add(new EmotiModel(639, "且_(・_・ )"));
            emotiModels.add(new EmotiModel(640, "(　ﾟДﾟ)⊃旦"));
            emotiModels.add(new EmotiModel(641, "( -_-)旦~"));
            emotiModels.add(new EmotiModel(642, "(*^◇^)_旦"));
            emotiModels.add(new EmotiModel(643, "(*･∀･)_Ω~"));
            emotiModels.add(new EmotiModel(644, "~旦_(^O^ )"));
            emotiModels.add(new EmotiModel(645, "(　 ゜Д゜)⊃旦"));
            emotiModels.add(new EmotiModel(646, "~~旦⊂(･∀･ )"));
            emotiModels.add(new EmotiModel(647, "ｰ( ￣▽)_皿~~"));
            emotiModels.add(new EmotiModel(648, "(*｀▽´)_旦~~"));
            emotiModels.add(new EmotiModel(649, "~~旦_(･o･;)"));
            emotiModels.add(new EmotiModel(650, "~(=^‥^)_旦~"));
            emotiModels.add(new EmotiModel(651, "且_(ﾟ◇ﾟ；)ノﾞ"));
            emotiModels.add(new EmotiModel(652, "(*´ｪ｀*)っ旦~"));
            emotiModels.add(new EmotiModel(653, "( ・・)つ-●●●"));
            emotiModels.add(new EmotiModel(654, "( ^-^)_旦””"));
            emotiModels.add(new EmotiModel(655, "((((´∀｀)＿旦～"));
            emotiModels.add(new EmotiModel(656, "( ´･ω･`)_且~"));
            emotiModels.add(new EmotiModel(657, "(*´-ω)o旦~┏┓"));
            emotiModels.add(new EmotiModel(658, "(*´・ω)o旦~┏┓"));
            emotiModels.add(new EmotiModel(659, "~~匸Pヽ(･ω･｀)"));
            emotiModels.add(new EmotiModel(660, "(○^ω^)_旦~~♪"));
            emotiModels.add(new EmotiModel(661, "~~旦_(-ω-｀｡)"));        }
        else if (i == 9) {
            getSupportActionBar().setTitle("Shy");
            emotiModels.add(new EmotiModel(662, "(^^ゞ"));
            emotiModels.add(new EmotiModel(663, "(〃▽〃)"));
            emotiModels.add(new EmotiModel(664, "(ノ▽〃)"));
            emotiModels.add(new EmotiModel(665, "（/｡＼)"));
            emotiModels.add(new EmotiModel(666, "(/ω＼)"));
            emotiModels.add(new EmotiModel(667, "(Ŏ艸Ŏ)"));
            emotiModels.add(new EmotiModel(668, "(^^;)"));
            emotiModels.add(new EmotiModel(669, "(〃ー〃)"));
            emotiModels.add(new EmotiModel(670, "(〃ω〃)"));
            emotiModels.add(new EmotiModel(671, "(〃艸〃)"));
            emotiModels.add(new EmotiModel(672, "(´つヮ⊂)"));
            emotiModels.add(new EmotiModel(673, "(♡´艸`)"));
            emotiModels.add(new EmotiModel(674, "(／≧ω＼)"));
            emotiModels.add(new EmotiModel(675, "ʕ*ﾉᴥﾉʔ"));
            emotiModels.add(new EmotiModel(676, "(/へ＼*)"));
            emotiModels.add(new EmotiModel(677, "(*ﾉ▽ﾉ)"));
            emotiModels.add(new EmotiModel(678, "(*ﾉωﾉ)"));
            emotiModels.add(new EmotiModel(679, "(*ﾉдﾉ)"));
            emotiModels.add(new EmotiModel(680, "(´～｀ヾ)"));
            emotiModels.add(new EmotiModel(681, "(ﾉ∇≦*)"));
            emotiModels.add(new EmotiModel(682, "(‘-’*)"));
            emotiModels.add(new EmotiModel(683, "(^◇^；)"));
            emotiModels.add(new EmotiModel(684, "|▽//)ゝ"));
            emotiModels.add(new EmotiModel(685, "(〃´∀｀)"));
            emotiModels.add(new EmotiModel(686, "ꈍ .̮ ꈍ"));
            emotiModels.add(new EmotiModel(687, "(〃∀〃)ゞ"));
            emotiModels.add(new EmotiModel(688, "( 〃．．)"));
            emotiModels.add(new EmotiModel(689, "(｡･･｡)"));
            emotiModels.add(new EmotiModel(690, "|´∀｀●)"));        }
        else if (i == 10) {
            getSupportActionBar().setTitle("Other");
            emotiModels.add(new EmotiModel(691, "( ͡ຈ╭͜ʖ╮͡ຈ )"));
            emotiModels.add(new EmotiModel(692, "( ͡ಠ ʖ̯ ͡ಠ)"));
            emotiModels.add(new EmotiModel(693, "( ͡~ ͜ʖ ͡~)"));
            emotiModels.add(new EmotiModel(694, "( ͡~ ͜ʖ ͡°)"));
            emotiModels.add(new EmotiModel(695, "( ͠° ͟ʖ ͡°)"));
            emotiModels.add(new EmotiModel(696, "( ͡ʘ╭͜ʖ╮͡ʘ)"));
            emotiModels.add(new EmotiModel(697, "( ͝סּ ͜ʖ͡סּ)"));
            emotiModels.add(new EmotiModel(698, "( ͡ᵔ ͜ʖ ͡ᵔ )"));
            emotiModels.add(new EmotiModel(699, "( ͡^ ͜ʖ ͡^ )"));
            emotiModels.add(new EmotiModel(700, "[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]"));
            emotiModels.add(new EmotiModel(701, "( ͡ຈ ͜ʖ ͡ຈ)"));
            emotiModels.add(new EmotiModel(702, "( ͡° ʖ̯ ͡°)"));
            emotiModels.add(new EmotiModel(703, "( ͡ ͜ʖ ͡ )"));
            emotiModels.add(new EmotiModel(704, "(☞ ͡° ͜ʖ ͡°)☞"));
            emotiModels.add(new EmotiModel(705, "ᕕ( ͡° ͜ʖ ͡° )ᕗ"));
            emotiModels.add(new EmotiModel(706, "( ͡° ͜ʖ ͡°)"));
            emotiModels.add(new EmotiModel(707, "( ͡°╭͜ʖ╮͡° )"));
            emotiModels.add(new EmotiModel(708, "(つ ͡° ͜ʖ ͡°)つ"));
            emotiModels.add(new EmotiModel(709, "( ͡⚆ ͜ʖ ͡⚆)"));
            emotiModels.add(new EmotiModel(710, "˓˓ ू༼ ⠁⃘ཀ ⠁⃘ू༽"));
            emotiModels.add(new EmotiModel(711, "(▀ ͜ʖ ͡°)"));
            emotiModels.add(new EmotiModel(712, "༼ ºل͟º ༽"));
            emotiModels.add(new EmotiModel(713, "┌༼ຈل͜ຈ༽┐"));
            emotiModels.add(new EmotiModel(714, "༼ ಠل͟ಠ༽"));
            emotiModels.add(new EmotiModel(715, "୧༼ ͡◉ل͜ ͡◉༽୨"));
            emotiModels.add(new EmotiModel(716, "ヽ༼ ಠ益ಠ ༽ﾉ"));
            emotiModels.add(new EmotiModel(717, "༼ ༎ຶ ෴ ༎ຶ༽"));
            emotiModels.add(new EmotiModel(718, "༼ ༏༏ີཻ༾ﾍ ༏༏ີཻ༾༾༽༽"));
            emotiModels.add(new EmotiModel(719, "༼･ิɷ･ิ༽"));
            emotiModels.add(new EmotiModel(720, "༼ ͒ ̶ ͒༽"));
            emotiModels.add(new EmotiModel(721, "༼༼;; ;°;ਊ°;༽"));
            emotiModels.add(new EmotiModel(722, "༼( ⁍ืེ – ⁍ื༽༽"));
            emotiModels.add(new EmotiModel(723, "༼•͟ ͜ •༽"));
            emotiModels.add(new EmotiModel(724, "༼•̃͡ ɷ•̃͡༽"));
            emotiModels.add(new EmotiModel(725, "༼ ͒ ͓ ͒༽"));
            emotiModels.add(new EmotiModel(726, "༼༭ຶཬ༤ຶ༽"));
            emotiModels.add(new EmotiModel(727, "༼ꉺˇɷˇꉺ༽"));
            emotiModels.add(new EmotiModel(728, "༼இɷஇ༽"));
            emotiModels.add(new EmotiModel(729, "༼✷ɷ✷༽"));
            emotiModels.add(new EmotiModel(730, "༼ԾɷԾ༽"));
            emotiModels.add(new EmotiModel(731, "༼≖ɷ≖༽"));
            emotiModels.add(new EmotiModel(732, "༼ꉺ✺ꉺ༽"));
            emotiModels.add(new EmotiModel(733, "༼ꉺლꉺ༽"));
            emotiModels.add(new EmotiModel(734, "ヽ༼ຈل͜ຈ༽ﾉ"));
            emotiModels.add(new EmotiModel(735, "༼ꉺ౪ꉺ༽"));
            emotiModels.add(new EmotiModel(736, "༼ꉺεꉺ༽"));
            emotiModels.add(new EmotiModel(737, "༼;´༎ຶ ༎ຶ ༽"));
            emotiModels.add(new EmotiModel(738, "༼⁰o⁰；༽"));
            emotiModels.add(new EmotiModel(739, "༼(⁽͇ˊ̑⁾ ἴृ ⁽ˋ̑⁾͇)༽"));
            emotiModels.add(new EmotiModel(740, "˓ ू༼ ்ͦ॔ཀ ்ͦ॓ू༽"));
            emotiModels.add(new EmotiModel(741, "༼ ु ்ͦ॔ཫ ்ͦ॓༽ु˒˒"));
            emotiModels.add(new EmotiModel(742, "／༼ ༏༏ີཻ༾ﾍ ༏༏ີཻ༾༾༽༽"));
            emotiModels.add(new EmotiModel(743, "༼ ்ͦ॔ཫ ்ͦ॓༽"));
            emotiModels.add(new EmotiModel(744, "༼ᶿ᷇ཫᶿ᷆༽"));
            emotiModels.add(new EmotiModel(745, "༼  ऀืົཀ  ऀืົ༽"));
            emotiModels.add(new EmotiModel(746, "༼՟ິͫཀ՟ິͫ༽"));
            emotiModels.add(new EmotiModel(747, "ˋ̧̧̖⁽⁽༼ ु˳̮̑̈༽ु⁾⁾ˋ̧̧̖♪"));
            emotiModels.add(new EmotiModel(748, "༼❁ɷ❁༽"));
            emotiModels.add(new EmotiModel(749, "༼ ຶཽཀ ຶཽ༽"));
            emotiModels.add(new EmotiModel(750, "ヽ༼၀-၀༽ﾉ"));
            emotiModels.add(new EmotiModel(751, "༼(❛)㇁(❛)༽"));
            emotiModels.add(new EmotiModel(752, "ヽ༼⊙_⊙༽ﾉ"));
            emotiModels.add(new EmotiModel(753, "༼⺤`皿′⺤༽"));
            emotiModels.add(new EmotiModel(754, "ヽ༼࿃っ࿃༽ﾉ"));
            emotiModels.add(new EmotiModel(755, "༼⌐■ل͟■༽"));
            emotiModels.add(new EmotiModel(756, "༼ง=ಠ益ಠ=༽ง"));
            emotiModels.add(new EmotiModel(757, "╰༼=ಠਊಠ=༽╯"));
            emotiModels.add(new EmotiModel(758, "ᕙ༼*◕_◕*༽ᕤ"));
            emotiModels.add(new EmotiModel(759, "ヽ༼ಢ_ಢ༽ﾉ"));
            emotiModels.add(new EmotiModel(760, "ヽ༼ ʘ̚ل͜ʘ̚༼◕_◕༽◉_◔ ༽ﾉ"));
            emotiModels.add(new EmotiModel(761, "┌༼ ⊘ _ ⊘ ༽┐"));
            emotiModels.add(new EmotiModel(762, "༼ : ౦ ‸ ౦ : ༽"));
            emotiModels.add(new EmotiModel(763, "༼∗ღ۝ღ∗༽"));
            emotiModels.add(new EmotiModel(764, "༼ง ͠ຈ ͟ل͜ ͠ຈ༽o:[]:::::::>"));
            emotiModels.add(new EmotiModel(765, "༼ᕗຈل͜ຈ༽ᕗ"));
            emotiModels.add(new EmotiModel(766, "ヽ༼ຈل͜ರೃ༽ﾉ"));
            emotiModels.add(new EmotiModel(767, "ヽヽ༼༼ຈຈل͜ل͜ຈຈ༽༽ﾉﾉ"));
            emotiModels.add(new EmotiModel(768, "༼ ᕤ◕◡◕ ༽ᕤ"));
            emotiModels.add(new EmotiModel(769, "ᕙ༼˵͠ ͠°ل͜͠ ͠°˵༽ᕗ"));
            emotiModels.add(new EmotiModel(770, "ᕦ༼::ಥ෴ಠೃ::༽ノ"));
            emotiModels.add(new EmotiModel(771, "༼ •̀ ں •́ ༽"));
            emotiModels.add(new EmotiModel(772, "♫ ┌༼ຈل͜ຈ༽┘ ♪"));
            emotiModels.add(new EmotiModel(773, "༼ ಥل͟ಥ ༽"));
            emotiModels.add(new EmotiModel(774, "༼ﾉƟ͆ل͜Ɵ͆༽ﾉ"));
            emotiModels.add(new EmotiModel(775, "༼୨Ɵ͆ل͜Ɵ͆༽୨"));
            emotiModels.add(new EmotiModel(776, "ヽ༼Ɵ͆ل͜Ɵ͆ヽ༽"));
            emotiModels.add(new EmotiModel(777, "୧༼Ɵ͆ل͜Ɵ͆୧༽"));
            emotiModels.add(new EmotiModel(778, "┌༼ຈل͜ຈ༽┘"));
            emotiModels.add(new EmotiModel(779, "へ༼ ✪ Ĺ̯ ✪ ༽و"));
            emotiModels.add(new EmotiModel(780, "c༼ ͡° ͜ʖ ͡° ༽⊃"));
            emotiModels.add(new EmotiModel(781, "༼ ಠ ͟ʖ ಠ ༽"));
            emotiModels.add(new EmotiModel(782, "୧༼ ” ✖ ‸ ✖ ” ༽୨"));
            emotiModels.add(new EmotiModel(783, "Ѱζ༼ᴼل͜ᴼ༽ᶘѰ"));
            emotiModels.add(new EmotiModel(784, "┏༼ ◉ ╭╮ ◉༽┓"));
            emotiModels.add(new EmotiModel(785, "ヽ༼ ☯‿☯༼ ಠ益ಠ༽◕ل͜◕༽つ"));
            emotiModels.add(new EmotiModel(786, "└༼ •́ ͜ʖ •̀ ༽┘"));
            emotiModels.add(new EmotiModel(787, "୧༼ ヘ ᗜ ヘ ༽୨"));
            emotiModels.add(new EmotiModel(788, "༼ ◔ ͜ʖ ◔ ༽"));
            emotiModels.add(new EmotiModel(789, "╰༼⇀︿⇀༽つ-]═──"));
            emotiModels.add(new EmotiModel(790, "乁༼☯‿☯✿༽ㄏ"));
        }  else if (i == 11) {
            getSupportActionBar().setTitle("Kiss");
            emotiModels.add(new EmotiModel(791, "ㄖꏁㄖ"));
            emotiModels.add(new EmotiModel(792, "ᴓᴈᴓ"));
            emotiModels.add(new EmotiModel(793, "|°з°|"));
            emotiModels.add(new EmotiModel(794, "(ΦзΦ)"));
            emotiModels.add(new EmotiModel(795, "˶⚈Ɛ⚈˵"));
            emotiModels.add(new EmotiModel(796, "（＿ε＿）"));
            emotiModels.add(new EmotiModel(797, "(‘ε’)"));
            emotiModels.add(new EmotiModel(798, "⁽˙³˙⁾"));
            emotiModels.add(new EmotiModel(799, "(-ε- )"));
            emotiModels.add(new EmotiModel(800, "•́ε•̀٥"));
            emotiModels.add(new EmotiModel(801, "(☆´3｀)"));
            emotiModels.add(new EmotiModel(802, "(・ε・｀)"));
            emotiModels.add(new EmotiModel(803, " Ⴀ͡კႠ͡"));
            emotiModels.add(new EmotiModel(804, "(ΘεΘ;)"));
            emotiModels.add(new EmotiModel(805, "(≡ε≡；)"));
            emotiModels.add(new EmotiModel(806, "（￣ε￣＠）"));
            emotiModels.add(new EmotiModel(807, "(´ε｀*)"));
            emotiModels.add(new EmotiModel(808, "（*＾3＾）"));
            emotiModels.add(new EmotiModel(809, "(*￣з￣)"));
            emotiModels.add(new EmotiModel(810, "(○ﾟε^○)"));
            emotiModels.add(new EmotiModel(811, "（。ˇ ⊖ˇ）"));
            emotiModels.add(new EmotiModel(812, "（○゜ε＾○）"));
            emotiModels.add(new EmotiModel(813, "|(￣3￣)|"));
            emotiModels.add(new EmotiModel(814, "ヾ(´〓｀)ﾉ"));
            emotiModels.add(new EmotiModel(815, "(~￣³￣)~"));
            emotiModels.add(new EmotiModel(816, "(ΘεΘʃƪ)"));
            emotiModels.add(new EmotiModel(817, "（￣ε￣ʃƪ）"));
            emotiModels.add(new EmotiModel(818, "（＠ーεー＠）"));
            emotiModels.add(new EmotiModel(819, "(*-(　　)"));
            emotiModels.add(new EmotiModel(820, "(๑♡3♡๑)"));
        }else if (i == 12) {
            getSupportActionBar().setTitle("Smile");
            emotiModels.add(new EmotiModel(821, "＾ω＾"));
            emotiModels.add(new EmotiModel(822, "▼ω▼"));
            emotiModels.add(new EmotiModel(823, "(´∀｀）"));
            emotiModels.add(new EmotiModel(824, "（＾∀＾）"));
            emotiModels.add(new EmotiModel(825, "(^○^)"));
            emotiModels.add(new EmotiModel(826, "(｀▽´)"));
            emotiModels.add(new EmotiModel(827, "米＾－＾米"));
            emotiModels.add(new EmotiModel(828, "(∩_∩)"));
            emotiModels.add(new EmotiModel(829, "(⌒∇⌒)"));
            emotiModels.add(new EmotiModel(830, "(☆▽☆)"));
            emotiModels.add(new EmotiModel(831, "(￣∇￣)"));
            emotiModels.add(new EmotiModel(832, "（￣ー+￣）"));
            emotiModels.add(new EmotiModel(833, "σ(^○^)"));
            emotiModels.add(new EmotiModel(834, "(^■^*)"));
            emotiModels.add(new EmotiModel(835, "(*^-^)"));
            emotiModels.add(new EmotiModel(836, "d(^^*)"));
            emotiModels.add(new EmotiModel(837, "(´w｀*)"));
            emotiModels.add(new EmotiModel(838, "|*￣ー￣|"));
            emotiModels.add(new EmotiModel(839, "{*≧∀≦}"));
            emotiModels.add(new EmotiModel(840, "(o^^o)"));
            emotiModels.add(new EmotiModel(841, "(o^∀^)"));
            emotiModels.add(new EmotiModel(842, "(*´ー`)"));
            emotiModels.add(new EmotiModel(843, "o(^▽^)o"));
            emotiModels.add(new EmotiModel(844, "o(^-^)o"));
            emotiModels.add(new EmotiModel(845, "(*´∇｀*)"));
            emotiModels.add(new EmotiModel(846, "（*´▽`*)"));
            emotiModels.add(new EmotiModel(847, "(=^_^=)"));
            emotiModels.add(new EmotiModel(848, "σ(ﾟｰ^*)"));
            emotiModels.add(new EmotiModel(849, "（●＞ω＜●）"));
            emotiModels.add(new EmotiModel(850, "y（^ヮ^）y"));
        }
        else if (i == 13) {
            getSupportActionBar().setTitle("Laugh");
            emotiModels.add(new EmotiModel(851, "(खਉख)"));
            emotiModels.add(new EmotiModel(852, "(ಡ艸ಡ)"));
            emotiModels.add(new EmotiModel(853, "（⌒▽⌒）"));
            emotiModels.add(new EmotiModel(854, "（＾ｖ＾）"));
            emotiModels.add(new EmotiModel(855, "（＞ｙ＜）"));
            emotiModels.add(new EmotiModel(856, "(＾艸＾)"));
            emotiModels.add(new EmotiModel(857, "(Ŏ艸Ŏ)"));
            emotiModels.add(new EmotiModel(858, "(亝艸亝)"));
            emotiModels.add(new EmotiModel(859, "(♡´艸`)"));
            emotiModels.add(new EmotiModel(860, "(●´艸`)"));
            emotiModels.add(new EmotiModel(861, "(≧艸≦*)"));
            emotiModels.add(new EmotiModel(862, "(*>艸<)"));
            emotiModels.add(new EmotiModel(863, "( ਊдਊ)"));
            emotiModels.add(new EmotiModel(864, "( ´艸｀)"));
            emotiModels.add(new EmotiModel(865, "(｡ˇ艸ˇ)"));
            emotiModels.add(new EmotiModel(866, "(o>艸<)"));
            emotiModels.add(new EmotiModel(867, "(^ц^ )"));
            emotiModels.add(new EmotiModel(868, "(☆Θ艸Θ)"));
            emotiModels.add(new EmotiModel(869, "（○´艸｀）"));
            emotiModels.add(new EmotiModel(870, "(*´艸｀)"));
            emotiModels.add(new EmotiModel(871, "（≧ｙ≦＊）"));
            emotiModels.add(new EmotiModel(872, "(*・艸・)"));
            emotiModels.add(new EmotiModel(873, "（　´∀｀）"));
            emotiModels.add(new EmotiModel(874, "(*≧艸≦)"));
            emotiModels.add(new EmotiModel(875, "( ╹ਊ╹)"));
            emotiModels.add(new EmotiModel(876, "( ՞ਊ՞)"));
            emotiModels.add(new EmotiModel(877, "(*´∀｀）"));
            emotiModels.add(new EmotiModel(878, "(✪ฺܫ✪ฺ)"));
            emotiModels.add(new EmotiModel(879, "( 〃´艸｀)"));
            emotiModels.add(new EmotiModel(880, "(❤ฺ￫艸￩)"));
        }

        recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(new EmoticonsAdapter(emotiModels,this));
    }

}